# Generated by Django 4.0.6 on 2022-07-29 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_alter_user_date_joined_alter_user_ext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 29, 15, 36, 17, 198807)),
        ),
        migrations.AlterField(
            model_name='user',
            name='staff_id',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
